"""
Extracted on: 2026-04-02

Description:
    Performs static analysis using inspect4py. Optimized for remote/background 
    execution via nohup. Includes enhanced logging and robust resume logic.

Usage:
    nohup python -u 2_inspect4py_analyse_awesome-python.py > analysis.log 2>&1 &
"""

import pickle
import subprocess
import os
import shutil
from pathlib import Path
from tqdm import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed

# --- PATH CONFIGURATION ---
PKL_PATH = Path("../data/AWESOME-PYTHON-REPOS.pkl")
WORKDIR = Path("../data/repos")
OUTDIR = Path("../data/output")
REQ_DIR = Path("../data/requirements")
MAX_WORKERS = 2

# Initialize directories
for d in [WORKDIR, OUTDIR, REQ_DIR]:
    d.mkdir(parents=True, exist_ok=True)


def process_single_repo(repo):
    """
    Worker: Clone -> Analyze -> Standardized Move
    """
    try:
        repo_dir = WORKDIR / repo
        repo_out = OUTDIR / repo
        repo_url = f"https://github.com/{repo}.git"

        # 1. Resume Logic (Check for completion sentinel)
        if (repo_out / "directory_info.json").exists():
            return f"[SKIPPED] {repo}"

        # 2. Shallow Clone
        if not repo_dir.exists():
            repo_dir.parent.mkdir(parents=True, exist_ok=True)
            subprocess.run(["git", "clone", "--depth", "1", repo_url, str(repo_dir)], check=False, capture_output=True)

        # 3. Static Analysis
        repo_out.mkdir(parents=True, exist_ok=True)
        inspect_cmd = [
            "inspect4py", "-i",
            str(repo_dir), "-o",
            str(repo_out), "-r", "-html", "-cl", "-cf", "-dt", "-si", "-ast", "-sc", "-ld", "-rm", "-md"
        ]
        subprocess.run(inspect_cmd, check=False, capture_output=True)

        # 4. Requirements Management (Standardized Naming)
        cwd = Path.cwd()
        pure_repo_name = repo.split('/')[-1]

        # Create a unique slug (owner_repo)
        repo_slug = repo.replace('/', '_')

        # Search for any requirements file generated by inspect4py
        for req_file in cwd.glob(f"requirements_{pure_repo_name}*.txt"):
            # Target format: owner_repo_requirements.txt
            new_filename = f"{repo_slug}_requirements.txt"
            target_path = REQ_DIR / new_filename
            shutil.move(str(req_file), str(target_path))

        return f"[SUCCESS] {repo}"
    except Exception as e:
        return f"[FAILED]  {repo} | Error: {str(e)}"


def main():
    if not PKL_PATH.exists():
        print(f"Error: Master list {PKL_PATH} not found.")
        return

    with open(PKL_PATH, "rb") as f:
        repos_dict = pickle.load(f)

    # Sorted list for predictable log output
    repo_list = sorted(list(repos_dict.keys()), key=str.lower)
    print(f"Executing Fresh Run for {len(repo_list)} repositories...")

    with ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(process_single_repo, repo): repo for repo in repo_list}

        with tqdm(total=len(repo_list), desc="Overall Progress") as pbar:
            for future in as_completed(futures):
                try:
                    # tqdm.write is crucial for nohup log readability
                    result = future.result()
                    tqdm.write(result)
                except Exception as e:
                    tqdm.write(f"Worker Error: {e}")
                pbar.update(1)

    print("\n--- Pipeline Finished: Data Clean and Standardized ---")


if __name__ == "__main__":
    main()
