"""
Executed on: 2026-04-01

Description:
    This is the second stage of the pipeline. It consumes the structured data 
    generated by '1_fetch_process_awesome-python.py' to perform deep static 
    analysis on each repository using the inspect4py framework.

Main Functionalities:
    1. Automated Cloning: Performs shallow clones (--depth 1) of 500+ repositories 
       to minimize disk I/O and network overhead.
    2. Parallel Processing: Utilizes multi-processing (ProcessPoolExecutor) to 
       leverage multi-core CPUs for simultaneous analysis.
    3. Static Analysis: Invokes 'inspect4py' to extract ASTs, call graphs, 
       metadata, and software invocation commands.
    4. Artifact Management: Organizes outputs into repository-specific folders 
       and centralizes requirements.txt files for dependency analysis.

Optimization Note:
    Configured with MAX_WORKERS to balance CPU-intensive AST generation and 
    I/O-intensive git operations.
"""
import pickle
import subprocess
import os
import shutil
from pathlib import Path
from tqdm import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed

# --- PATH CONFIGURATION ---
PKL_PATH = Path("../data/AWESOME-PYTHON-REPOS.pkl")
WORKDIR = Path("../data/repos")
OUTDIR = Path("../data/output")
REQ_DIR = Path("../data/requirements")

# --- EXECUTION SETTINGS ---
# Adjust based on CPU core count. 4-8 recommended for high-load AST extraction.
MAX_WORKERS = 4

# Ensure environment is ready
for d in [WORKDIR, OUTDIR, REQ_DIR]:
    d.mkdir(parents=True, exist_ok=True)


def process_single_repo(repo):
    """
    Worker function: Clones a single repo and runs the full inspect4py suite.
    """
    try:
        # Standardize local paths
        repo_dir = WORKDIR / repo
        repo_out = OUTDIR / repo
        repo_url = f"https://github.com/{repo}.git"

        # 1. Clone Stage (Shallow)
        if not repo_dir.exists():
            repo_dir.parent.mkdir(parents=True, exist_ok=True)
            # Use capture_output to keep the main console clean
            subprocess.run(["git", "clone", "--depth", "1", repo_url, str(repo_dir)], check=False, capture_output=True)

        # 2. Analysis Stage (inspect4py)
        repo_out.mkdir(parents=True, exist_ok=True)
        # Full extraction flags
        inspect_cmd = [
            "inspect4py", "-i",
            str(repo_dir), "-o",
            str(repo_out), "-r", "-html", "-cl", "-cf", "-dt", "-si", "-ast", "-sc", "-ld", "-rm", "-md"
        ]

        subprocess.run(inspect_cmd, check=False, capture_output=True)

        # 3. Post-Analysis: Centralize requirements files
        cwd = Path.cwd()
        # Get only the repository name (e.g., "awesome-python" from "vinta/awesome-python")
        pure_repo_name = repo.split('/')[-1]
        # Search for files named "requirements_awesome-python*.txt"
        for req_file in cwd.glob(f"requirements_{pure_repo_name}*.txt"):
            # To avoid filename collisions in REQ_DIR, we rename it to "owner_repo_requirements.txt"
            # This ensures "user1/tools" and "user2/tools" don't overwrite each other
            new_name = f"{repo.replace('/', '_')}_{req_file.name}"
            target = REQ_DIR / new_name
            shutil.move(str(req_file), str(target))
            print(f"Moved {req_file} -> {target}")

        return f"Success: {repo}"
    except Exception as e:
        return f"Fail: {repo} | Reason: {str(e)}"


def main():
    # 1. Load data from Stage 1
    if not PKL_PATH.exists():
        print(f"Error: {PKL_PATH} not found. Please run '1_fetch_process_awesome-python.py' first.")
        return

    with open(PKL_PATH, "rb") as f:
        repos = pickle.load(f)

    repo_list = list(repos.keys())
    print(f"Executing Phase 2: Analyzing {len(repo_list)} repositories...")

    # 2. Parallel Processing Loop
    with ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
        # Submit all tasks to the process pool
        futures = {executor.submit(process_single_repo, repo): repo for repo in repo_list}

        # tqdm progress bar tracks completion of futures
        with tqdm(total=len(repo_list), desc="Overall Extraction Progress") as pbar:
            for future in as_completed(futures):
                # Retrieve result to catch potential process-level exceptions
                # result = future.result()
                pbar.update(1)


if __name__ == "__main__":
    main()
